In [1]:
import sys
sys.path.insert(0, '/cndd/fangming/CEMBA/snmcseq_dev')

from __init__ import *
from __init__jupyterlab import *

In [2]:
f = '/cndd/fangming/CEMBA/data/MOp_all/results_final/miniatlas_joint_clusterings.tsv'
df = pd.read_csv(f, sep='\t')
print(df.shape)
df.head()

/cndd/fangming/venvs/conda_dobro/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(408885, 15)

,sample,joint_embedding_x,joint_embedding_y,modality,modality_name,single_modality_cluster,single_modality_annot,joint_cluster_round2,joint_cluster_round2_annot,joint_cluster_round3,joint_cluster_round3_annot,joint_cluster_round3_color,joint_cluster_round4,joint_cluster_round4_annot,joint_cluster_round4_color
0,snmcseq_gene_2C_M_0,0.471629,-3.134735,snmcseq_gene,DNA methylation,L4-IT-Rorb_Rorb-Tenm2,L4-IT-Rorb_Rorb-Tenm2,1-1,L5 IT Rspo1_1,1-1-1,L5 IT Rspo1_1,#3CBC78,1-1-1-1,L5 IT Rspo1_1,#3CBC78
1,snmcseq_gene_2C_M_1,-2.414973,-12.098081,snmcseq_gene,DNA methylation,L23-IT-Cux2,L23-IT-Cux2,4-2,L2/3 IT,4-2-1,L2/3 IT,#6F836B,4-2-1-1,L2/3 IT,#6F836B
2,snmcseq_gene_2C_M_100,-1.446751,-12.051894,snmcseq_gene,DNA methylation,L23-IT-Cux2,L23-IT-Cux2,4-1,L2/3 IT,4-1-1,L2/3 IT,#6F836B,4-1-1-1,L2/3 IT,#6F836B
3,snmcseq_gene_2C_M_1000,-1.901734,-13.660591,snmcseq_gene,DNA methylation,L23-IT-Cux2,L23-IT-Cux2,4-2,L2/3 IT,4-2-1,L2/3 IT,#6F836B,4-2-1-1,L2/3 IT,#6F836B
4,snmcseq_gene_2C_M_1001,-0.981086,-11.936621,snmcseq_gene,DNA methylation,L23-IT-Cux2,L23-IT-Cux2,4-1,L2/3 IT,4-1-1,L2/3 IT,#6F836B,4-1-1-1,L2/3 IT,#6F836B

In [13]:
a = df.groupby('joint_cluster_round3').agg({'joint_cluster_round3_color': lambda x: x.value_counts(ascending=False).index[0]})
a.index = [type.replace('-', '_') for type in a.index]

a.to_csv('/cndd/fangming/CEMBA/data/MOp_all/annoj/round3/round3_colors.tsv', header=True, index=True, sep='\t')
a.head()

       joint_cluster_round3_color
1_1_1                     #3CBC78
1_2_1                     #3CBC45
1_2_2                     #5DDB65
10_1_1                    #FFFF00
2_1_1                     #338C5E

In [17]:
f = '/cndd/fangming/CEMBA/data/MOp_all/annoj/round3/annotations.tsv'
df2 = pd.read_csv(f, sep='\t')
df2.head()


fout = '/cndd/fangming/CEMBA/data/MOp_all/annoj/round3/annotations_order.tsv'
df2.sort_values('annotation').to_csv(fout, header=True, index=False, sep='\t')